2020-11-22 12:12:22.936 [error] <0.332.0>@Elixir.GenServer:call Supervisor 'Elixir.ConferenceEvents.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.4162327840.1156972545.240649>,opts => [{timeout,15000},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at undefined exit with reason no such process or port in call to 'Elixir.GenServer':call('Elixir.DBConnection.Watcher', {watch,'Elixir.DBConnection.ConnectionPool.Supervisor',{'Elixir.DBConnection.ConnectionPool.Pool',...}}, infinity) in context start_error
2020-11-22 12:22:01.082 [error] <0.332.0>@Elixir.GenServer:call Supervisor 'Elixir.ConferenceEvents.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.423276187.1695678469.10051>,opts => [{timeout,15000},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at undefined exit with reason no such process or port in call to 'Elixir.GenServer':call('Elixir.DBConnection.Watcher', {watch,'Elixir.DBConnection.ConnectionPool.Supervisor',{'Elixir.DBConnection.ConnectionPool.Pool',...}}, infinity) in context start_error
2020-11-22 12:22:01.082 [error] <0.331.0> Supervisor 'Elixir.ConferenceEvents.Supervisor' had child 'Elixir.ConferenceEvents.Repo' started with 'Elixir.ConferenceEvents.Repo':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.DBConnection.ConnectionPool',{noproc,{'Elixir.GenServer',call,['Elixir.DBConnection.Watcher',{watch,'Elixir.DBConnection.ConnectionPool.Supervisor',{'Elixir.DBConnection.ConnectionPool.Pool',{<0.333.0>,#Ref<0.423276187.1695678469.10052>,'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ConferenceEvents.Repo'},{telemetry_prefix,[conference_events,repo]},{otp_app,conference_events},{timeout,15000},{username,<<"ph...">>},...]}}},...]}}}} in context start_error
2020-11-22 12:29:52.359 [error] <0.459.0> Failed to start Ranch listener 'Elixir.ConferenceEventsWeb.Endpoint.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4000}]) for reason eaddrinuse (address already in use)
2020-11-22 12:29:52.379 [error] <0.457.0> Supervisor {<0.457.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.ConferenceEventsWeb.Endpoint.HTTP', ranch_tcp) at undefined exit with reason {listen_error,'Elixir.ConferenceEventsWeb.Endpoint.HTTP',eaddrinuse} in context start_error
